blank_issues_enabled: false
contact_links:
  - name: Discord Community
    url: https://dub.sh/kultiverse-discord
    about: Join our Discord Community to ask questions, get support and provide feedback! Issues are for bugs/feature requests.
